---
  version: "3"
  networks: 
    web: 
      driver: "bridge"
  services: 
    jira-grafana:
      # Copy settings.env.example to settings.env
      env_file: settings.env
      build:
        context: .
        dockerfile: Dockerfile-dev
      volumes:
        - ".:/app"
      ports: 
        - "3005 :3005"
      networks: 
        - "web"
    grafana:
      image: grafana/grafana
      environment:
        - "GF_INSTALL_PLUGINS=grafana-simple-json-datasource"
      ports:
        - "3010:3005"
      networks: 
        - "web"